package com.ots.aipassportphotomaker.common.utils

// Created by amanullah on 20/09/2025.
// Copyright (c) 2025 Ozi Publishing. All rights reserved.
object AnalyticsConstants {
    const val ACTION_VIEW = "action_view"
    const val ACTION_TYPE = "action_type"
    const val CONTENT_TYPE = "content_type"
    const val OPENED = "opened"
    const val CLOSED = "closed"
    const val CLICKED = "clicked"
    const val ADDED = "added"
    const val REMOVED = "removed"
    const val PRESSED = "pressed"
    const val ACTION = "action"
    const val SHOWED = "showed"
    const val DISMISSED = "dismissed"
    const val CHECKED = "checked"
    const val SELECTED = "selected"
    const val UNSELECT = "unselect"
    const val ALLOWED = "allowed"
    const val DENIED = "denied"
    const val REQUESTED = "requested"
    const val LOADED = "loaded"
    const val CANCELED = "canceled"
    const val FAILED = "failed"
    const val SUCCESS = "success"
    const val ERROR = "error"
    const val STARTED = "started"
    const val COMPLETED = "completed"
    const val SKIPPED = "skipped"
    const val PAUSED = "paused"
    const val RESUMED = "resumed"
    const val RETRY = "retry"
    const val RETRYING = "retrying"
    const val CONNECTED = "connected"
    const val DISCONNECTED = "disconnected"
    const val PREMIUM_USER = "premium_user"
    const val FREE_USER = "free_user"
}